name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build and push Java-17
        uses: docker/build-push-action@v2
        with:
          context: ./java-17
          file: ./java-17/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/java-node:java-17
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/java-node:java-17-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/java-node:java-17-buildcache,mode=max

      -
        name: Build and push Java-8
        uses: docker/build-push-action@v2
        with:
          context: ./java-8
          file: ./java-8/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/java-node:java-8
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/java-node:java-8-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/java-node:java-8-buildcache,mode=max

